"""
catalog.py — Static catalog of known ClearPass REST API endpoints.

This dict is exposed as an MCP resource (``clearpass://api-catalog``) so
AI clients can load the full endpoint list as context without a tool call.
It is also returned by the ``clearpass_list_apis`` tool with optional
category filtering.

The entries follow the format::

    "METHOD  /path  - Description"

and are organized by the same category groupings used in the official
Aruba ClearPass REST API Guide.
"""
from __future__ import annotations

CLEARPASS_APIS: dict[str, list[str]] = {
    "ApiOperations (v1)": [
        "POST   /oauth                             - Generate OAuth2 access token",
        "GET    /oauth/me                          - Get current authenticated user info",
        "GET    /oauth/privileges                  - Get current token privileges",
        "GET    /oauth/all-privileges              - List all system-defined privileges",
    ],
    "Identities (v1)": [
        "--- Endpoints & Devices ---",
        "GET    /endpoint                          - List all endpoints",
        "POST   /endpoint                          - Create a new endpoint",
        "GET    /endpoint/{id}                     - Get endpoint by ID",
        "PATCH  /endpoint/{id}                     - Update endpoint by ID",
        "DELETE /endpoint/{id}                     - Delete endpoint by ID",
        "GET    /endpoint/mac-address/{mac}        - Get endpoint by MAC address",
        "PATCH  /endpoint/mac-address/{mac}        - Update endpoint by MAC address",
        "DELETE /endpoint/mac-address/{mac}        - Delete endpoint by MAC address",
        "GET    /device                            - List device accounts",
        "POST   /device                            - Create device account",
        "GET    /device/mac/{macaddr}              - Get device by MAC",
        "PATCH  /device/{id}                       - Update device by ID",
        "DELETE /device/{id}                       - Delete device by ID",
        "--- Users & Guests ---",
        "GET    /local-user                        - List local users",
        "POST   /local-user                        - Create local user",
        "GET    /local-user/user-id/{id}           - Get local user by ID",
        "PATCH  /local-user/{id}                   - Update local user",
        "DELETE /local-user/{id}                   - Delete local user",
        "GET    /guest                             - List guest accounts",
        "POST   /guest                             - Create guest account",
        "GET    /guest/username/{user}             - Get guest by username",
        "GET    /guest/{id}                        - Get guest by ID",
        "PATCH  /guest/{id}                        - Update guest account",
        "DELETE /guest/{id}                        - Delete guest account",
        "--- API & Others ---",
        "GET    /api-client                        - List API clients",
        "GET    /static-host-list                  - List static host lists",
        "GET    /external-account                  - List external accounts",
    ],
    "PolicyElements (v1)": [
        "--- AuthMethod & AuthSource ---",
        "GET    /auth-method                       - List authentication methods",
        "POST   /auth-method                       - Create new authentication method",
        "GET    /auth-method/name/{name}           - Get method by name",
        "GET    /auth-source                       - List authentication sources",
        "GET    /auth-source/name/{name}           - Get source by name",
        "--- NetworkDevice & Groups ---",
        "GET    /network-device                    - List network devices (NAS)",
        "POST   /network-device                    - Create new network device",
        "GET    /network-device/name/{name}        - Get device by name",
        "PATCH  /network-device/{id}               - Update network device",
        "DELETE /network-device/{id}               - Delete network device",
        "GET    /network-device-group              - List network device groups",
        "POST   /network-device-group              - Create new network device group",
        "--- RADIUS Proxy & Roles ---",
        "GET    /proxy-target                      - List RADIUS proxy targets",
        "GET    /role                              - List roles",
        "POST   /role                              - Create new role",
        "GET    /role/name/{name}                  - Get role by name",
        "--- Role Mapping & Services ---",
        "GET    /role-mapping                      - List role mapping policies",
        "GET    /role-mapping/name/{name}          - Get role mapping by name",
        "GET    /config/service                    - List CPPM configuration services",
        "GET    /config/service/name/{name}        - Get service by name",
        "PATCH  /config/service/{id}/enable        - Enable a service",
        "PATCH  /config/service/{id}/disable       - Disable a service",
    ],
    "SessionControl (v1)": [
        "--- Active Sessions ---",
        "GET    /session                           - List active sessions",
        "GET    /session/{id}                      - Get active session details",
        "POST   /session/{id}/disconnect           - Disconnect active session",
        "POST   /session/{id}/reauthorize          - Reauthorize active session",
        "--- Bulk Actions ---",
        "POST   /session-action/disconnect         - Bulk disconnect by filter",
        "POST   /session-action/coa                - Bulk reauthorize (CoA)",
        "GET    /session-action/{action_id}        - Get status of bulk action",
    ],
    "CertificateAuthority (v1)": [
        "--- Onboard Certificates ---",
        "GET    /certificate                       - List Onboard certificates",
        "POST   /certificate/new                   - Create new CSR and private key",
        "POST   /certificate/import                - Import CA or trusted certificate",
        "POST   /certificate/{id}/sign             - Sign a CSR",
        "POST   /certificate/{id}/revoke           - Revoke a certificate",
        "--- Onboard Device & User ---",
        "GET    /onboard/device                    - List Onboard devices",
        "GET    /onboard/device/{id}               - Get Onboard device details",
        "GET    /user                              - List Onboard users",
        "GET    /user/{id}                         - Get Onboard user details",
    ],
    "EndpointVisibility & OnGuard (v1)": [
        "--- Agentless & Profiler ---",
        "GET    /agentless-onguard/settings        - List Agentless OnGuard settings",
        "GET    /profiler-subnet-mapping           - List profiler subnet mappings",
        "POST   /device-profiler/device-fingerprint - Post device fingerprint attributes",
        "GET    /fingerprint                       - List known fingerprints",
        "--- Network Scan & Custom Scripts ---",
        "GET    /config/network-scan               - List Network Scan configurations",
        "POST   /config/network-scan               - Add a Network Scan",
        "GET    /onguard-custom-script             - List OnGuard custom scripts",
        "--- Global & Zone Settings ---",
        "GET    /onguard/global-settings           - Get OnGuard global settings",
        "GET    /onguard/policy-manager-zones      - Get PM Zones / Auth Server IPs",
    ],
    "GuestActions & Config (v1)": [
        "--- Guest Operations ---",
        "GET    /guest/{id}/receipt/{tpl}          - Generate guest receipt (HTML)",
        "GET    /guest/{id}/pass/{tpl}             - Generate digital pass",
        "POST   /guest/{id}/sendreceipt/sms        - Resend receipt via SMS",
        "POST   /guest/{id}/sendreceipt/smtp       - Resend receipt via Email",
        "--- Pages & Templates ---",
        "GET    /weblogin                          - List web login pages",
        "GET    /template/print                    - List print templates",
        "GET    /template/pass                     - List pass templates",
        "--- Guest Settings ---",
        "GET    /guest/authentication              - Guest auth configuration",
        "GET    /guestmanager                      - Guest manager settings",
    ],
    "GlobalServerConfiguration (v1)": [
        "--- Admins & Profiles ---",
        "GET    /admin-user                        - List administrator users",
        "GET    /admin-privilege                   - List administrator privileges",
        "GET    /operator-profile                  - List operator profiles",
        "--- Licenses & Attributes ---",
        "GET    /application-license               - List application licenses",
        "GET    /application-license/summary       - View license summary",
        "GET    /attribute                         - List custom attributes",
        "--- Cluster & Sync ---",
        "POST   /cluster/db-sync                   - Sync subscriber with publisher",
        "GET    /cluster/parameters                - Get cluster-wide parameters",
        "--- Policies & Messaging ---",
        "GET    /admin-user/password-policy        - Get admin password policy",
        "GET    /local-user/password-policy        - Get local user password policy",
        "GET    /messaging-setup                   - View messaging configuration",
    ],
    "LocalServerConfiguration (v1)": [
        "--- Server Info ---",
        "GET    /server/version                    - Get server versions",
        "GET    /cppm-version                      - Get CPPM specific version",
        "GET    /server/fips                       - Get FIPS mode info",
        "--- Cluster & Control ---",
        "GET    /cluster/server                    - List cluster nodes",
        "GET    /cluster/server/{uuid}             - Get node configuration",
        "GET    /server/service/{uuid}             - List all services on node",
        "PATCH  /server/service/{uuid}/{svc}/start - Start a server service",
        "--- Access & SNMP ---",
        "GET    /server/access-control/{uuid}      - View node access controls",
        "GET    /server/snmp/{uuid}                - View node SNMP settings",
    ],
    "Integrations & Extensions (v1)": [
        "--- Extensions ---",
        "GET    /extension/instance                - List installed extensions",
        "POST   /extension/instance/{id}/restart   - Restart extension",
        "GET    /extension/instance/{id}/log       - Get extension logs",
        "GET    /extension/store                   - Query extension store",
        "--- Context Servers ---",
        "GET    /endpoint-context-server           - List context servers",
        "POST   /context-server-action             - List context actions",
        "--- Syslog & Insight ---",
        "GET    /syslog-target                     - List syslog targets",
        "GET    /syslog-export-filter              - List export filters",
        "GET    /device-insight                    - Device Insight integration",
    ],
    "Logs & Audit (v1)": [
        "GET    /audit-record                      - Audit logs",
        "GET    /system-event                      - List system events",
        "GET    /login-audit/{name}                - Previous logins for admin",
        "--- Insight Endpoint Info ---",
        "GET    /insight/endpoint/mac/{mac}        - Get endpoint info by MAC",
        "GET    /insight/endpoint/ip/{ip}          - Lookup endpoint by IP",
        "GET    /insight/endpoint/time-range       - Lookup by time range",
    ],
    "PlatformCertificates (v1)": [
        "--- Trust & Revocation ---",
        "GET    /cert-trust-list                   - List trust certificates",
        "GET    /revocation-list                   - List revocation list (CRL)",
        "--- Server & Client Certs ---",
        "GET    /server-cert                       - List server certificates",
        "GET    /client-cert                       - List client certificates",
        "GET    /service-cert                      - List service certificates",
        "POST   /cert-sign-request                 - Post certificate sign request",
    ],
    "ToolsAndUtilities (v1)": [
        "POST   /email/send                        - Send manual email",
        "POST   /sms/send                          - Send manual SMS",
        "GET    /random-mpsk                       - Generate random MPSK",
        "GET    /random-password                   - Generate random password",
    ],
}
